# This cake file will be run on push to remote.
# It will reject in the following cases
#    - Not formatted with csharpier. To solve this, open cmd and execute ```dotnet cake _format.cake```
#    - Build Fails. Build errors exist. Fix issues.
#    - Tests or coverage fails. See details in _coverage.cake, test runner, and/or coverage report. 

name: .NET

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Restore tools
              run: dotnet tool restore
            - name: Check format
              run: dotnet cake _push.cake
